### ISSUE TITLE
训练数据

### ISSUE THREAD

**Issue by forever112233** [FanChiMao/CMFNet#1]
请问您在训练中得到最好的SSIM和PSNR的数值是否还有记录？，经过一段时间训练发现，训练中SSIM和PSNR在第六次 
               epoch后，直到30多次，SSIM没有变化，PSNR也变化很少，请问您是否遇到这种问题？

**Comment by FanChiMao** [comment]
在 [training_log.zip](https://github.com/FanChiMao/CMFNet/releases/download/v0.0/training_log.zip)中有利用tensorboard儲存的訓練驗證曲線。
於terminal輸入 tensorboard --logdir [儲存log檔的資料夾位置]。
下圖為輸入以上指令後，以dehaze任務為例:
由於初始設定150 epochs，但發現50個epoch後validation曲線有下降趨勢，故中斷訓練。
原因主要可能是訓練資料數據結構無法很好的支持驗證資料的圖像。
同樣與dehaze為例，訓練資料我們使用I-Haze與O-Haze，驗證測試於D-Haze。
很明顯D-Haze的haze程度相較於I、O-Haze高出許多，使得模型已經收斂。
沒有變化的問題在dehaze任務特別明顯，其他兩個任務較不會有這個問題。
值得注意的是在論文中沒提到的部分，也謝謝有人詢問提醒，即我們的訓練數量問題，
詳細部分(包括超參數設定)已更新至README file，可以多加注意!

- Details of Hyperparameters
	```
	-------------------------------------------------
	GoPro dataset:
	Training patches: 33648 (2103 x 16)
	Validation: 1111
	Initial learning rate: 2e-4
	Final learning rate: 1e-6
	Training epochs: 150 (120 is enough)
  Training time (on single 2080ti): about 10 days

	Raindrop dataset:
	Training patches: 6888 (861 x 8)
	Validation: 1228 (307 x 4)
	Initial learning rate: 2e-4
	Final learning rate: 1e-6
	Training epochs: 150 (100 is enough)
  Training time (on single 1080ti): about 2.5 days
  
	IO-Haze dataset:
	Training patches: 15000 (75 x 200)
	Validation: 55
	Initial learning rate: 1e-4
	Final learning rate: 1e-6
	Training epochs: 150 (50 is enough)
  Training time (on single 1080ti): about 3 days
	-------------------------------------------------
	```  
![擷取](https://user-images.githubusercontent.com/85726287/167783389-1abe4880-7e04-484c-a629-80dba393b625.PNG)

**Comment by forever112233** [comment]
作者，您的其他参数或者程序是否有稍微的修改之处，如图所示，是我的设定，经过您的提醒，和您提到的一致，但训练依 
        旧不理想，图中是否需要其他变化？
![参数设定](https://user-images.githubusercontent.com/105329520/167812937-91523685-eaba-4346-bb52-c8617bf31bab.JPG)

           经过训练，不知为何，学习率一开始总会跳动，训练过程中第一次训练的学习率不是设定的1e-4，而是别的数值，总会跳 
           动一下，如图所示 （曲线图，batchsize=4,这是损失会少一半左右，但batchsize=2,依旧会跳动）， 与作者的有差距，请 
           问作者是否知道这是什么原因，这会对初始训练数据有影响么？第二次训练的学习率才会达到初始设定值。
           另外在参数和作者您提供的相同情况下（batchsize=2的图片），训练数据PSNR以及SSIM总会相对作者的低许多，差距 
           大，请问作者能否有思路解答？，麻烦您了，感谢！
![曲线图](https://user-images.githubusercontent.com/105329520/167819310-33ca047f-19df-420a-84eb-ecfad3d1be6a.JPG)
![batchzize=4,](https://user-images.githubusercontent.com/105329520/167817161-5c18e87c-a1dd-4394-8cca-df3c78d029a3.JPG)
![batchsize=2](https://user-images.githubusercontent.com/105329520/167817309-09fc5431-efd2-40bd-a5a8-a5a50a483e2a.JPG)
