### ISSUE TITLE
推理的时候总是显存不足

### ISSUE THREAD

**Issue by sihuo521** [FanChiMao/CMFNet#2]
每次只推理一张图片

**Comment by sihuo521** [comment]
![image](https://user-images.githubusercontent.com/36940636/173482037-51dfb7d6-b5e1-4273-81cf-0a8f5f2410ea.png)

**Comment by sihuo521** [comment]
python demo.py --input_dir '图片路径' --result_dir '结果路径' --weights '模型路径'

**Comment by FanChiMao** [comment]
您的顯卡是什麼型號呢? 我們的CMFNet測試於GTX GPU 1080Ti (RAM: 11G)，經測試後，若使用GPU執行單張圖篇(batch size = 1)，最少您的GPU顯存需要有4G左右，若硬體設備無法達到此需求，可以考慮使用cpu進行測試(把demo.py中所有的.cuda()移除)。 但若要訓練CMFNet，可能還是需要升級一下硬體設備😳

**Comment by FanChiMao** [comment]
您的顯卡是什麼型號呢? 或是您測試的圖像大小是多大呢? 我們的CMFNet測試於GTX GPU 1080Ti (RAM: 11G)。 最大的測試圖像(1280x720: GoPro dataset)需要大概顯存9.3G左右，若硬體設備無法達到此需求，可以考慮使用cpu進行測試(把demo.py中所有的.cuda()移除)。 但若要訓練CMFNet，可能還是要測試看看。
