### ISSUE TITLE
result

### ISSUE THREAD

**Issue by RC-Qiao** [FanChiMao/CMFNet#8]
你可以给出Dehaze 对比实验和你网络的结果图连接么 谢谢！

**Comment by userHLN** [comment]
你好 deraindrop测试集直接用307张图片用来测试？

**Comment by FanChiMao** [comment]
@hdcxqrc 前往業界工作，回覆較晚請見諒..
Dehaze 的對比實驗 我都是找原論文程式跑的，但因為輸入圖片太大張 (1600 x 1200) 一般的顯卡 (1080ti, 2080ti)無法 inference，所以是借其它電腦 (3090) 來跑結果的。 我找了下我的硬碟發現沒有存到，若你目前有較好的硬體配置，可以直接載 pretrained model 來跑我的 code，可以得到一樣的結果。

@userHLN deraindrop 測試集在原論文有提到有分 TestA 與 TestB，其中 TestA 是有較好的對齊結果的，TestB 有一些是 GT 沒對齊好的 (TestA is a subset of testB, which contains 58 pairs of good aligned images. TestB has 249 image pairs with a small portion of images which are not perfectly aligned.) 我們是以 TestA 做為測試結果，所以是用 58張。
